### ISSUE TITLE
Can you also export the `create` function?

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form-templates-bootstrap#4]
I noticed that the [`create`](https://github.com/gcanti/tcomb-form-templates-bootstrap/blob/master/src/checkbox.js#L13) function is not being exported from the file. That makes it impossible to use the overrides facility of this function. Just for the sake of extensibility, can you import this function as well? Thanks.

**Comment by gcanti** [comment]
Aren't `create` and `clone` equivalent?

**Comment by volkanunsal** [comment]
Ah, excellent. Didn't notice that. Carry on then. :)
